plugins {
    id 'java'
    id 'application'
    id 'eclipse'
}

allprojects {
    group = 'br.angarion.dev'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['app/src/main/java']
            exclude 'br/angarion/dev/api/**'
            exclude 'br/angarion/dev/engine/**'
            exclude 'br/angarion/dev/processors/**'
            exclude 'br/angarion/dev/infra/**'
        }
    }
    test {
        java {
            srcDirs = ['app/src/test/java']
        }
    }
}

dependencies {
    implementation project(':api')
    annotationProcessor project(':processors')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

application {
    mainClass.set('br.angarion.dev.App')
}
