plugins {
    id 'java'
}

group = 'br.angarion.dev'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['app/src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['app/src/test/java']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'it.unimi.dsi:fastutil:8.5.18'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
