plugins {
    id 'java'
    id 'com.google.osdetector' version '1.7.3'
}

dependencies {
    implementation project(':engine')
    implementation project(':api')

    implementation "io.netty.incubator:netty-incubator-codec-native-quic:0.0.70.Final:${osdetector.classifier}"
    implementation 'it.unimi.dsi:fastutil:8.5.18'

    runtimeOnly 'org.bouncycastle:bcprov-jdk18on:1.80'
    runtimeOnly 'org.bouncycastle:bcpkix-jdk18on:1.80'
}
